name: Run Python Cron Job

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at midnight UTC
  workflow_dispatch:     # Optional: allows you to manually trigger the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    env:  
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12' 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: python main.py
